version: 2

sources:
  - name: erp
    description: 'Fonte de dados do sistema ERP da Adventure Works, contendo informações detalhadas sobre vendas e transações comerciais.'
    database: adventure_works
    schema: sap_adw
    tables:
      - name: address
      - name: businessentityaddress
      - name: countryregion
      - name: creditcard
      - name: customer
      - name: employee
      - name: person
      - name: product
      - name: productcategory
      - name: productsubcategory
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesperson
      - name: salesreason
      - name: salesterritory
      - name: stateprovince
      - name: store